server:
  port: ${SERVER_PORT:8082}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/wildcore_core}
    username: ${DATABASE_USER:root}
    driver-class-name: com.mysql.jdbc.Driver
    password: ${DATABASE_PASSWORD:rootpassword}

  mail:
    host: ${SMTP_HOST:example.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:admin@example.com}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          starttls:
            enable: ${SMTP_STARTTLS:true}
          auth: true

wildcore:
  mail:
    from: ${SMTP_USERNAME:admin@example.com}
    from_name: ${SMTP_FROM_NAME:wildcore}
    user:
      sent: true
      template: request_beta.html
    admin:
      template: request_beta_admin.html
      sent: true
      addresses:
       - ${ADMIN_EMAIL:admin@example.com}

